from pathlib import Path
from engine.state import load_level, initial_game_state
from engine.validator import apply_move
from models import Direction, Status

LEVEL_DIR = Path(__file__).parent / "levels"

CHAR_MAP = {
    "R": Direction.RIGHT,
    "L": Direction.LEFT,
    "U": Direction.UP,
    "D": Direction.DOWN,
    "_": Direction.SWITCH,
}

SOLUTIONS = [
    (1,  "RDDRRDR"),
    (2,  "URDRRRRUUDRDRRURU"),
    (3,  "RURRRULDRUURRRDDDRU"),
    (4,  "ULURRURRRRRRDRDDDDDRULLLLLLD"),
    (5,  "LLLRLLLLLDRDDRRRRDRRRRLLLLDLLLLLL"),
    (6,  "RRRDDRDDRDRULLLUULUUURRDRRULDDRRDDR"),
    (7,  "DLURRRRRDRLULLLLLDRDRDRRRUURDLURUURRRDRDRDLU"),
    (8,  "RRDDDD_UURR"),
    (9,  "RDRRRRRRUR_D_D_RRRRRU_LLLLLD"),
    (10, "RR_DDRRDRDDDDD_LDDDRDDDL_LL_D_L_D_LULLLDURRRDR_LRURUUUULLULDLLLLL"),
    (11, "RRRRULDDDRRRDLULLLUURURRDRULLLDDLLLUURUULDRURDL"),
    (12, "LDRURDLURURURURRRDDDLURUUULLLRRRDDDLDRURDLURUURUDLDDDLURULULLLDDL"),
    (13, "UULDRDRDLUUUULLLLLLLDDDRULDRDDRDDRURRRRRULDLUU"),
    (14, "RRRRULLDRRRDDDDLLLDRRDRRLLUURRULUDDLLDLURRRUUUULLLLLLURDLLLLLDDDRDR"),
    (15, "RRRRUU_UUUUURRRUURRRDRDU_LLL_D_L_ULULLLD_LLLLLDLLDDDLDRURRRRRRR"),
    (16, "RRRR_RD_RU_RLLLRRRRLLLLLD_RU_RRRR"),
    (17, "DDDDDLURRRRRURRRLLLDLLLLUUUUUURRRRDRRRRDLURDURDLUURDLLURDLLLLULLLLDDDDDDRRRRURRRDDULULLLDLLLUUULURRRRRDRRR"),
    (18, "DLURRRRUUDDLLLDRULLDRURRRDDUULLLULDRULLDDDDRRLLUUUURRDRULDDRULDRURRRRRDDDRULDDRULDLUR"),
    (19, "RRRRRRRRDRULLLLLLDRURRRRRDDDDDLLLLLDLURRRRRRULDLLLLLDDDDRRRLLLLLLUU"),
    (20, "DLDRDLUURUULLLDLLURDDLDDLDURUURUURRRDLD_U_LLLLDDDDD_LD_RRRRD"),
    (21, "RDLULDRURRURRRULDDDUUURDLLLDLLDLURDRULDRULDRDDRDDRRRUUDDLLULDRRRUUUURRR"),
    (22, "RURRRRDRDDDLDURUUULURDLULULLDLLLDRURDLDDDRDULUUURULDRURURRRDRRRRU"),
    (23, "RDDRURRRRRULDRULLLUUUURRRRUDLLLLDDDDLLLLLLLLLUUURRUDLURDDRDDDRRDRUUUUUURDLU"),
    (24, "DLDRDLUUDDRULURDRRUURULDRURRRRLLLLLDRLURDLURRRRRRRDLRURRR"),
    (25, "URDLURDLURRRRULULLURLDRRDDLLLLDRRURRRUURRRURDLUURDLURDL"),
    (26, "UULLLDLLLDRURRUURRDRRDRRUU_UUULLLDLLLLLDD_LLULLLDLLLLLL_LD_DDDUURURRRURRRDRRUU_UUULLLDLDDDDRRR_LLULLLDLDDDDRRL"),
    (27, "RRRRRULDRURDLLLLLLDRULLDRURRRRURRRRDDDLDDDLLLDLUUUURDLLLLLLLULDDRULDRUL"),
    (28, "LDDDRDLURDDRRDDRRRUUULULULULDRRDRDRDRRDLDLLUUULULULLULLDLURRRDRDRDRDRDLL_L_D_L_D_LLLLUULLLLD_LLLLLLUULLLLU"),
    (29, "RDLULDRURDDRRLLUULDRULDLULUULLRRDDRDRURDLURUURRLLDDDDDDRRLLUUUULLLLLLRRRRDLURRRRRRLLLLLULDDDDLLLDRULDRUL"),
    (30, "DRDDRRURRDRRRRUDLLLLULLLDDLURRRRRRUUURRRURDDDLLDLDRUURDLDLLLLULLDLLULDLURUDLDRURDRRULDDLURRRRRRRULUUURRRURULLLLLDL"),
    (31, "ULDLLUUUUDDDDRRRULDRUUUURULDDRULDLLLDDDLDDUURUUULLLLDRULDDDDDLURLURDRURRURRDRRRULDRUUUUURDL"),
    (32, "UULDRURURDLRULDLDLURDLURURURDLLDDDLDLLULDRRRUUUUURURRUDLLDLDDDDDLLLLURLDRRRRUUUUURURRUDLLDLDDDDDLLLURDRRURUUURRULDLDLDRULLULLLLLD"),
    (33, "RRRRULDDLURUURRDRDRULLURDRDDRDLDDRRUDLLUURULUULULDRULLLDDDLDLLDLU"),
]

all_passed = True
for level_id, seq in SOLUTIONS:
    level = load_level(LEVEL_DIR / f"level{level_id}.txt")
    state = initial_game_state(level)

    final_status = Status.OK
    fail_move = None

    for i, ch in enumerate(seq):
        direction = CHAR_MAP[ch]
        result = apply_move(direction, state, level)
        state = result.next_state
        final_status = result.status
        if final_status != Status.OK:
            fail_move = (i + 1, ch)
            break

    if final_status == Status.WIN:
        print(f"level {level_id:2d}: WIN  ({len(seq)} moves)")
    elif fail_move:
        print(f"level {level_id:2d}: LOSS at move {fail_move[0]} ('{fail_move[1]}')")
    else:
        print(f"level {level_id:2d}: no WIN after {len(seq)} moves")
