"""
build_paper_assets.py — regenerate paper figures and tables from data/.

Outputs:
    paper/tables/leaderboard.tex             — overwritten from data/leaderboard.json
    paper/figures/cost_vs_rhae.tex           — pgfplots Pareto plot
    paper/figures/level_<id>.png             — level snapshots (via render_level_image)

Pgfplots is preferred over Matplotlib for figures embedded in the paper because the
fonts and colors flow from the document class.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

PAPER_TABLES = ROOT / "paper" / "tables"
PAPER_FIGURES = ROOT / "paper" / "figures"
DATA = ROOT / "data"


# Approximate USD per 1M tokens for each model (provider-published rates as of 2026-04).
# These are illustrative; the leaderboard table cites them in the paper's notes section.
_PRICE_PER_MTOK = {
    "claude-opus-4-6":         {"prompt": 15.00, "completion": 75.00},
    "claude-sonnet-4-6":       {"prompt":  3.00, "completion": 15.00},
    "gpt-5.4":                 {"prompt":  5.00, "completion": 15.00},
    "gpt-5.4-nano":            {"prompt":  0.30, "completion":  1.20},
    "oai-gpt-5-2-2025-12-11":  {"prompt":  5.00, "completion": 15.00},
    "oai-gpt-4.1-2025-04-14":  {"prompt":  3.00, "completion": 12.00},
}


def _base_model(model_tag: str) -> str:
    """Strip the trailing _high/_none suffix to recover the base model id."""
    for suf in ("_high", "_none", "_low", "_medium"):
        if model_tag.endswith(suf):
            return model_tag[: -len(suf)]
    return model_tag


def _effort(model_tag: str) -> str:
    for suf in ("_high", "_none", "_low", "_medium"):
        if model_tag.endswith(suf):
            return suf[1:]
    return "none"


def _provider(model_tag: str) -> str:
    base = _base_model(model_tag).lower()
    if "claude" in base:
        return "Anthropic"
    if "gpt" in base or "oai" in base:
        return "OpenAI"
    return "Other"


def _cost_usd(prompt_toks: int, completion_toks: int, model_tag: str) -> float:
    base = _base_model(model_tag)
    rate = _PRICE_PER_MTOK.get(base, {"prompt": 0.0, "completion": 0.0})
    return (prompt_toks / 1e6) * rate["prompt"] + (completion_toks / 1e6) * rate["completion"]


# ---------------------------------------------------------------------------
# Leaderboard table
# ---------------------------------------------------------------------------


def write_leaderboard_table(leaderboard: dict) -> Path:
    rows = leaderboard["rows"]
    rows = [r for r in rows if r["mode"] == "turn"]
    rows.sort(key=lambda r: -r["hlg_rhae"])

    lines = [
        "% Auto-generated by scripts/build_paper_assets.py.",
        "% Re-run after extract_leaderboard.py to refresh.",
        "\\begin{table}[h]",
        "\\centering",
        "\\caption{Initial frontier-model HLG-RHAE on the full scoring set (levels 1--33), turn mode, parallel runs. Numbers are computed by \\texttt{scripts/extract\\_leaderboard.py} against the v0.1 baseline ($h_l = L_l$, optimal length). Cost computed at provider-published per-token rates as of March 2026.}",
        "\\label{tab:leaderboard}",
        "\\small",
        "\\begin{tabular}{@{}llrrrrr@{}}",
        "\\toprule",
        "\\textbf{Provider} & \\textbf{Model} & \\textbf{Effort} & \\textbf{HLG-RHAE} & \\textbf{Won} & \\textbf{Tokens} & \\textbf{Cost (USD)} \\\\",
        "\\midrule",
    ]

    for r in rows:
        provider = _provider(r["model_tag"])
        base = _base_model(r["model_tag"]).replace("_", "\\_")
        effort = _effort(r["model_tag"])
        won = r["levels_won"]
        attempted = r["levels_attempted"]
        rhae_pct = f"{r['hlg_rhae'] * 100:.2f}\\%"
        total_toks = r["total_tokens"]
        cost = _cost_usd(r["total_prompt_tokens"], r["total_completion_tokens"], r["model_tag"])
        lines.append(
            f"{provider} & \\texttt{{{base}}} & {effort} & {rhae_pct} & "
            f"{won}/{attempted} & {total_toks:,} & \\${cost:,.2f} \\\\"
        )

    if not rows:
        lines.append("\\multicolumn{7}{c}{\\textit{No log data yet --- run \\texttt{main.py} first.}} \\\\")

    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]

    out = PAPER_TABLES / "leaderboard.tex"
    out.write_text("\n".join(lines) + "\n")
    return out


# ---------------------------------------------------------------------------
# Cost-vs-RHAE Pareto plot (pgfplots)
# ---------------------------------------------------------------------------


def write_cost_vs_rhae_plot(leaderboard: dict) -> Path:
    rows = [r for r in leaderboard["rows"] if r["mode"] == "turn"]
    points = []
    for r in rows:
        cost = _cost_usd(r["total_prompt_tokens"], r["total_completion_tokens"], r["model_tag"])
        if cost > 0 or r["hlg_rhae"] > 0:
            points.append((cost, r["hlg_rhae"] * 100, r["model_tag"]))

    pts_str = "\n".join(
        f"        ({cost:.4f}, {rhae:.4f})"
        for cost, rhae, _label in points
    ) or "        (0, 0)"

    tex = f"""\
% Auto-generated by scripts/build_paper_assets.py
\\begin{{tikzpicture}}
\\begin{{axis}}[
    width=0.85\\linewidth, height=0.55\\linewidth,
    xmode=log,
    xlabel={{API cost (USD, log scale)}},
    ylabel={{HLG-RHAE (\\%)}},
    grid=both,
    grid style={{dashed, gray!30}},
    only marks,
    nodes near coords,
    nodes near coords align={{above}},
    point meta=explicit symbolic,
]
\\addplot[mark=*, mark size=2pt] coordinates {{
{pts_str}
}};
\\end{{axis}}
\\end{{tikzpicture}}
"""
    out = PAPER_FIGURES / "cost_vs_rhae.tex"
    out.write_text(tex)
    return out


# ---------------------------------------------------------------------------
# Level snapshots
# ---------------------------------------------------------------------------


def write_level_snapshots(level_ids: list[str]) -> list[Path]:
    from scripts.render_level_image import render_level_to_png  # type: ignore

    out_paths: list[Path] = []
    for lid in level_ids:
        path = PAPER_FIGURES / f"{lid}.png"
        try:
            render_level_to_png(lid, path)
            out_paths.append(path)
        except SystemExit as exc:
            print(f"  skip {lid}: {exc}", file=sys.stderr)
    return out_paths


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def main() -> int:
    lb_path = DATA / "leaderboard.json"
    if not lb_path.exists():
        print("error: data/leaderboard.json missing. Run scripts/extract_leaderboard.py first.",
              file=sys.stderr)
        return 1

    leaderboard = json.loads(lb_path.read_text())

    PAPER_TABLES.mkdir(parents=True, exist_ok=True)
    PAPER_FIGURES.mkdir(parents=True, exist_ok=True)

    out = write_leaderboard_table(leaderboard)
    print(f"wrote {out}")
    out = write_cost_vs_rhae_plot(leaderboard)
    print(f"wrote {out}")

    snaps = write_level_snapshots(["level0", "level8", "level17", "level33"])
    for p in snaps:
        print(f"wrote {p}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
